name: .NET Core

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]
    
env:
  SOLUTION_PATH: "src/Trakx.Coinbase.ApiClient.sln"
  CoinbaseCustodyApiConfiguration__AccessKey: ${{secrets.COINBASE_CUSTODY_ACCESSKEY}}
  CoinbaseCustodyApiConfiguration__PassPhrase: ${{secrets.COINBASE_CUSTODY_PASSPHRASE}}
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore ${{env.SOLUTION_PATH}}
    - name: Build
      run: dotnet build ${{env.SOLUTION_PATH}} --configuration Release --no-restore
    - name: Test
      run: dotnet test ${{env.SOLUTION_PATH}} --no-restore --logger GitHubActions --verbosity normal
