name: Publish nuget package

on: 
  workflow_dispatch:
    inputs:
      semverIncrementLevel:
        description: 'Level of the semver (major.minor.patch) to be increased to get the new package version.'
        required: true
        default: 'patch'
  push:
    branches: 
      - master

env:
  SOLUTION_PATH: "src/Trakx.Coinbase.ApiClient.sln"
  PACKAGE_NAME: Trakx.Coinbase.Custody.ApiClient
  PROJECT_PATH: "src/Trakx.Coinbase.Custody.ApiClient/Trakx.Coinbase.Custody.ApiClient.csproj"
  CoinbaseCustodyApiConfiguration__AccessKey: ${{secrets.COINBASE_CUSTODY_ACCESSKEY}}
  CoinbaseCustodyApiConfiguration__PassPhrase: ${{secrets.COINBASE_CUSTODY_PASSPHRASE}}

jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: checkout
      uses: actions/checkout@v2

    - name: Bump version
      id: bumpVersion
      uses: trakx/bump-version-action@v6
      with:
        semverIncrementLevel: ${{github.event.inputs.semverIncrementLevel}}
        releaseBranches: master
        githubToken: ${{secrets.GITHUB_TOKEN}}
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.x
    
    - name: Add github nuget source
      run: dotnet nuget add source "https://nuget.pkg.github.com/trakx/index.json" --name "github" --username "trakx-bot" --password ${{secrets.TRAKX_BOT_READONLY_PAT}} --store-password-in-clear-text

    - name: Install dependencies
      run: dotnet restore ${{env.SOLUTION_PATH}}
    
    - name: Remove github source
      run: dotnet nuget remove source "github"
    
    - name: Build
      run: dotnet build ${{env.SOLUTION_PATH}} --configuration Release --no-restore
    
    - name: Test
      run: dotnet test ${{env.SOLUTION_PATH}} --no-restore --verbosity normal

    - name: Package
      run: dotnet pack ${{env.PROJECT_PATH}} --no-build --configuration Release --output ./nuget/ -p:PackageVersion=${{ steps.bumpVersion.outputs.fullVersion }}

    - name: Publish
      # https://github.com/NuGet/Home/issues/8580
      run: dotnet nuget push ./nuget/*.nupkg --api-key ${{secrets.GITHUB_TOKEN}} --source "https://nuget.pkg.github.com/trakx/index.json"

    - name: push version tag
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        CUSTOM_TAG: v${{steps.bumpVersion.outputs.fullVersion}}
